version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBIT_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
    ports:
      - 5672:5672
      - 15672:15672
